package models

// Generated 1:1 MySQL models

type ItemTemplateFull struct {
	Entry                     int            `json:"entry"`
	Class                     int            `json:"class"`
	Subclass                  int            `json:"subclass"`
	Name                      string         `json:"name"`
	Description               string         `json:"description"`
	DisplayId                 int            `json:"display_id"`
	Quality                   int            `json:"quality"`
	Flags                     int            `json:"flags"`
	BuyCount                  int            `json:"buy_count"`
	BuyPrice                  int            `json:"buy_price"`
	SellPrice                 int            `json:"sell_price"`
	InventoryType             int            `json:"inventory_type"`
	AllowableClass            int            `json:"allowable_class"`
	AllowableRace             int            `json:"allowable_race"`
	ItemLevel                 int            `json:"item_level"`
	RequiredLevel             int            `json:"required_level"`
	RequiredSkill             int            `json:"required_skill"`
	RequiredSkillRank         int            `json:"required_skill_rank"`
	RequiredSpell             int            `json:"required_spell"`
	RequiredHonorRank         int            `json:"required_honor_rank"`
	RequiredCityRank          int            `json:"required_city_rank"`
	RequiredReputationFaction int            `json:"required_reputation_faction"`
	RequiredReputationRank    int            `json:"required_reputation_rank"`
	MaxCount                  int            `json:"max_count"`
	Stackable                 int            `json:"stackable"`
	ContainerSlots            int            `json:"container_slots"`
	StatType1                 int            `json:"stat_type1"`
	StatValue1                int            `json:"stat_value1"`
	StatType2                 int            `json:"stat_type2"`
	StatValue2                int            `json:"stat_value2"`
	StatType3                 int            `json:"stat_type3"`
	StatValue3                int            `json:"stat_value3"`
	StatType4                 int            `json:"stat_type4"`
	StatValue4                int            `json:"stat_value4"`
	StatType5                 int            `json:"stat_type5"`
	StatValue5                int            `json:"stat_value5"`
	StatType6                 int            `json:"stat_type6"`
	StatValue6                int            `json:"stat_value6"`
	StatType7                 int            `json:"stat_type7"`
	StatValue7                int            `json:"stat_value7"`
	StatType8                 int            `json:"stat_type8"`
	StatValue8                int            `json:"stat_value8"`
	StatType9                 int            `json:"stat_type9"`
	StatValue9                int            `json:"stat_value9"`
	StatType10                int            `json:"stat_type10"`
	StatValue10               int            `json:"stat_value10"`
	Delay                     int            `json:"delay"`
	RangeMod                  float64        `json:"range_mod"`
	AmmoType                  int            `json:"ammo_type"`
	DmgMin1                   float64        `json:"dmg_min1"`
	DmgMax1                   float64        `json:"dmg_max1"`
	DmgType1                  int            `json:"dmg_type1"`
	DmgMin2                   float64        `json:"dmg_min2"`
	DmgMax2                   float64        `json:"dmg_max2"`
	DmgType2                  int            `json:"dmg_type2"`
	DmgMin3                   float64        `json:"dmg_min3"`
	DmgMax3                   float64        `json:"dmg_max3"`
	DmgType3                  int            `json:"dmg_type3"`
	DmgMin4                   float64        `json:"dmg_min4"`
	DmgMax4                   float64        `json:"dmg_max4"`
	DmgType4                  int            `json:"dmg_type4"`
	DmgMin5                   float64        `json:"dmg_min5"`
	DmgMax5                   float64        `json:"dmg_max5"`
	DmgType5                  int            `json:"dmg_type5"`
	Block                     int            `json:"block"`
	Armor                     int            `json:"armor"`
	HolyRes                   int            `json:"holy_res"`
	FireRes                   int            `json:"fire_res"`
	NatureRes                 int            `json:"nature_res"`
	FrostRes                  int            `json:"frost_res"`
	ShadowRes                 int            `json:"shadow_res"`
	ArcaneRes                 int            `json:"arcane_res"`
	Spellid1                  int            `json:"spellid_1"`
	Spelltrigger1             int            `json:"spelltrigger_1"`
	Spellcharges1             int            `json:"spellcharges_1"`
	Spellppmrate1             float64        `json:"spellppmrate_1"`
	Spellcooldown1            int            `json:"spellcooldown_1"`
	Spellcategory1            int            `json:"spellcategory_1"`
	Spellcategorycooldown1    int            `json:"spellcategorycooldown_1"`
	Spellid2                  int            `json:"spellid_2"`
	Spelltrigger2             int            `json:"spelltrigger_2"`
	Spellcharges2             int            `json:"spellcharges_2"`
	Spellppmrate2             float64        `json:"spellppmrate_2"`
	Spellcooldown2            int            `json:"spellcooldown_2"`
	Spellcategory2            int            `json:"spellcategory_2"`
	Spellcategorycooldown2    int            `json:"spellcategorycooldown_2"`
	Spellid3                  int            `json:"spellid_3"`
	Spelltrigger3             int            `json:"spelltrigger_3"`
	Spellcharges3             int            `json:"spellcharges_3"`
	Spellppmrate3             float64        `json:"spellppmrate_3"`
	Spellcooldown3            int            `json:"spellcooldown_3"`
	Spellcategory3            int            `json:"spellcategory_3"`
	Spellcategorycooldown3    int            `json:"spellcategorycooldown_3"`
	Spellid4                  int            `json:"spellid_4"`
	Spelltrigger4             int            `json:"spelltrigger_4"`
	Spellcharges4             int            `json:"spellcharges_4"`
	Spellppmrate4             float64        `json:"spellppmrate_4"`
	Spellcooldown4            int            `json:"spellcooldown_4"`
	Spellcategory4            int            `json:"spellcategory_4"`
	Spellcategorycooldown4    int            `json:"spellcategorycooldown_4"`
	Spellid5                  int            `json:"spellid_5"`
	Spelltrigger5             int            `json:"spelltrigger_5"`
	Spellcharges5             int            `json:"spellcharges_5"`
	Spellppmrate5             float64        `json:"spellppmrate_5"`
	Spellcooldown5            int            `json:"spellcooldown_5"`
	Spellcategory5            int            `json:"spellcategory_5"`
	Spellcategorycooldown5    int            `json:"spellcategorycooldown_5"`
	Bonding                   int            `json:"bonding"`
	PageText                  int            `json:"page_text"`
	PageLanguage              int            `json:"page_language"`
	PageMaterial              int            `json:"page_material"`
	StartQuest                int            `json:"start_quest"`
	LockId                    int            `json:"lock_id"`
	Material                  int            `json:"material"`
	Sheath                    int            `json:"sheath"`
	RandomProperty            int            `json:"random_property"`
	SetId                     int            `json:"set_id"`
	MaxDurability             int            `json:"max_durability"`
	AreaBound                 int            `json:"area_bound"`
	MapBound                  int            `json:"map_bound"`
	Duration                  int            `json:"duration"`
	BagFamily                 int            `json:"bag_family"`
	DisenchantId              int            `json:"disenchant_id"`
	FoodType                  int            `json:"food_type"`
	MinMoneyLoot              int            `json:"min_money_loot"`
	MaxMoneyLoot              int            `json:"max_money_loot"`
	WrappedGift               int            `json:"wrapped_gift"`
	ExtraFlags                int            `json:"extra_flags"`
	OtherTeamEntry            int            `json:"other_team_entry"`
	ScriptName                string         `json:"script_name"`
	DroppedByNpcs             []int          `json:"dropped_by_npcs,omitempty"` // populated during sync
	SpellDescriptions         map[int]string `json:"-"`                         // extracted from item page, not persisted
}

type CreatureTemplateFull struct {
	Entry              int     `json:"entry"`
	DisplayId1         int     `json:"display_id1"`
	DisplayId2         int     `json:"display_id2"`
	DisplayId3         int     `json:"display_id3"`
	DisplayId4         int     `json:"display_id4"`
	MountDisplayId     int     `json:"mount_display_id"`
	Name               string  `json:"name"`
	Subname            string  `json:"subname"`
	GossipMenuId       int     `json:"gossip_menu_id"`
	LevelMin           int     `json:"level_min"`
	LevelMax           int     `json:"level_max"`
	HealthMin          int     `json:"health_min"`
	HealthMax          int     `json:"health_max"`
	ManaMin            int     `json:"mana_min"`
	ManaMax            int     `json:"mana_max"`
	Armor              int     `json:"armor"`
	Faction            int     `json:"faction"`
	NpcFlags           int     `json:"npc_flags"`
	SpeedWalk          float64 `json:"speed_walk"`
	SpeedRun           float64 `json:"speed_run"`
	Scale              float64 `json:"scale"`
	DetectionRange     float64 `json:"detection_range"`
	CallForHelpRange   float64 `json:"call_for_help_range"`
	LeashRange         float64 `json:"leash_range"`
	Rank               int     `json:"rank"`
	XpMultiplier       float64 `json:"xp_multiplier"`
	DmgMin             float64 `json:"dmg_min"`
	DmgMax             float64 `json:"dmg_max"`
	DmgSchool          int     `json:"dmg_school"`
	AttackPower        int     `json:"attack_power"`
	DmgMultiplier      float64 `json:"dmg_multiplier"`
	BaseAttackTime     int     `json:"base_attack_time"`
	RangedAttackTime   int     `json:"ranged_attack_time"`
	UnitClass          int     `json:"unit_class"`
	UnitFlags          int     `json:"unit_flags"`
	DynamicFlags       int     `json:"dynamic_flags"`
	BeastFamily        int     `json:"beast_family"`
	TrainerType        int     `json:"trainer_type"`
	TrainerSpell       int     `json:"trainer_spell"`
	TrainerClass       int     `json:"trainer_class"`
	TrainerRace        int     `json:"trainer_race"`
	RangedDmgMin       float64 `json:"ranged_dmg_min"`
	RangedDmgMax       float64 `json:"ranged_dmg_max"`
	RangedAttackPower  int     `json:"ranged_attack_power"`
	Type               int     `json:"type"`
	TypeFlags          int     `json:"type_flags"`
	LootId             int     `json:"loot_id"`
	PickpocketLootId   int     `json:"pickpocket_loot_id"`
	SkinningLootId     int     `json:"skinning_loot_id"`
	HolyRes            int     `json:"holy_res"`
	FireRes            int     `json:"fire_res"`
	NatureRes          int     `json:"nature_res"`
	FrostRes           int     `json:"frost_res"`
	ShadowRes          int     `json:"shadow_res"`
	ArcaneRes          int     `json:"arcane_res"`
	SpellId1           int     `json:"spell_id1"`
	SpellId2           int     `json:"spell_id2"`
	SpellId3           int     `json:"spell_id3"`
	SpellId4           int     `json:"spell_id4"`
	SpellListId        int     `json:"spell_list_id"`
	PetSpellListId     int     `json:"pet_spell_list_id"`
	SpawnSpellId       int     `json:"spawn_spell_id"`
	Auras              string  `json:"auras"`
	GoldMin            int     `json:"gold_min"`
	GoldMax            int     `json:"gold_max"`
	AiName             string  `json:"ai_name"`
	MovementType       int     `json:"movement_type"`
	InhabitType        int     `json:"inhabit_type"`
	Civilian           int     `json:"civilian"`
	RacialLeader       int     `json:"racial_leader"`
	Regeneration       int     `json:"regeneration"`
	EquipmentId        int     `json:"equipment_id"`
	TrainerId          int     `json:"trainer_id"`
	VendorId           int     `json:"vendor_id"`
	MechanicImmuneMask int     `json:"mechanic_immune_mask"`
	SchoolImmuneMask   int     `json:"school_immune_mask"`
	ImmunityFlags      int     `json:"immunity_flags"`
	FlagsExtra         int     `json:"flags_extra"`
	PhaseQuestId       int     `json:"phase_quest_id"`
	ScriptName         string  `json:"script_name"`
}

type QuestTemplateFull struct {
	Entry                  int     `json:"entry"`
	Method                 int     `json:"Method"`
	Zoneorsort             int     `json:"ZoneOrSort"`
	Minlevel               int     `json:"MinLevel"`
	Maxlevel               int     `json:"MaxLevel"`
	Questlevel             int     `json:"QuestLevel"`
	Type                   int     `json:"Type"`
	Requiredclasses        int     `json:"RequiredClasses"`
	Requiredraces          int     `json:"RequiredRaces"`
	Requiredskill          int     `json:"RequiredSkill"`
	Requiredskillvalue     int     `json:"RequiredSkillValue"`
	Requiredcondition      int     `json:"RequiredCondition"`
	Repobjectivefaction    int     `json:"RepObjectiveFaction"`
	Repobjectivevalue      int     `json:"RepObjectiveValue"`
	Requiredminrepfaction  int     `json:"RequiredMinRepFaction"`
	Requiredminrepvalue    int     `json:"RequiredMinRepValue"`
	Requiredmaxrepfaction  int     `json:"RequiredMaxRepFaction"`
	Requiredmaxrepvalue    int     `json:"RequiredMaxRepValue"`
	Suggestedplayers       int     `json:"SuggestedPlayers"`
	Limittime              int     `json:"LimitTime"`
	Questflags             int     `json:"QuestFlags"`
	Specialflags           int     `json:"SpecialFlags"`
	Prevquestid            int     `json:"PrevQuestId"`
	Nextquestid            int     `json:"NextQuestId"`
	Exclusivegroup         int     `json:"ExclusiveGroup"`
	Nextquestinchain       int     `json:"NextQuestInChain"`
	Srcitemid              int     `json:"SrcItemId"`
	Srcitemcount           int     `json:"SrcItemCount"`
	Srcspell               int     `json:"SrcSpell"`
	Title                  string  `json:"Title"`
	Details                string  `json:"Details"`
	Objectives             string  `json:"Objectives"`
	Offerrewardtext        string  `json:"OfferRewardText"`
	Requestitemstext       string  `json:"RequestItemsText"`
	Endtext                string  `json:"EndText"`
	Objectivetext1         string  `json:"ObjectiveText1"`
	Objectivetext2         string  `json:"ObjectiveText2"`
	Objectivetext3         string  `json:"ObjectiveText3"`
	Objectivetext4         string  `json:"ObjectiveText4"`
	Reqitemid1             int     `json:"ReqItemId1"`
	Reqitemid2             int     `json:"ReqItemId2"`
	Reqitemid3             int     `json:"ReqItemId3"`
	Reqitemid4             int     `json:"ReqItemId4"`
	Reqitemcount1          int     `json:"ReqItemCount1"`
	Reqitemcount2          int     `json:"ReqItemCount2"`
	Reqitemcount3          int     `json:"ReqItemCount3"`
	Reqitemcount4          int     `json:"ReqItemCount4"`
	Reqsourceid1           int     `json:"ReqSourceId1"`
	Reqsourceid2           int     `json:"ReqSourceId2"`
	Reqsourceid3           int     `json:"ReqSourceId3"`
	Reqsourceid4           int     `json:"ReqSourceId4"`
	Reqsourcecount1        int     `json:"ReqSourceCount1"`
	Reqsourcecount2        int     `json:"ReqSourceCount2"`
	Reqsourcecount3        int     `json:"ReqSourceCount3"`
	Reqsourcecount4        int     `json:"ReqSourceCount4"`
	Reqcreatureorgoid1     int     `json:"ReqCreatureOrGOId1"`
	Reqcreatureorgoid2     int     `json:"ReqCreatureOrGOId2"`
	Reqcreatureorgoid3     int     `json:"ReqCreatureOrGOId3"`
	Reqcreatureorgoid4     int     `json:"ReqCreatureOrGOId4"`
	Reqcreatureorgocount1  int     `json:"ReqCreatureOrGOCount1"`
	Reqcreatureorgocount2  int     `json:"ReqCreatureOrGOCount2"`
	Reqcreatureorgocount3  int     `json:"ReqCreatureOrGOCount3"`
	Reqcreatureorgocount4  int     `json:"ReqCreatureOrGOCount4"`
	Reqspellcast1          int     `json:"ReqSpellCast1"`
	Reqspellcast2          int     `json:"ReqSpellCast2"`
	Reqspellcast3          int     `json:"ReqSpellCast3"`
	Reqspellcast4          int     `json:"ReqSpellCast4"`
	Rewchoiceitemid1       int     `json:"RewChoiceItemId1"`
	Rewchoiceitemid2       int     `json:"RewChoiceItemId2"`
	Rewchoiceitemid3       int     `json:"RewChoiceItemId3"`
	Rewchoiceitemid4       int     `json:"RewChoiceItemId4"`
	Rewchoiceitemid5       int     `json:"RewChoiceItemId5"`
	Rewchoiceitemid6       int     `json:"RewChoiceItemId6"`
	Rewchoiceitemcount1    int     `json:"RewChoiceItemCount1"`
	Rewchoiceitemcount2    int     `json:"RewChoiceItemCount2"`
	Rewchoiceitemcount3    int     `json:"RewChoiceItemCount3"`
	Rewchoiceitemcount4    int     `json:"RewChoiceItemCount4"`
	Rewchoiceitemcount5    int     `json:"RewChoiceItemCount5"`
	Rewchoiceitemcount6    int     `json:"RewChoiceItemCount6"`
	Rewitemid1             int     `json:"RewItemId1"`
	Rewitemid2             int     `json:"RewItemId2"`
	Rewitemid3             int     `json:"RewItemId3"`
	Rewitemid4             int     `json:"RewItemId4"`
	Rewitemcount1          int     `json:"RewItemCount1"`
	Rewitemcount2          int     `json:"RewItemCount2"`
	Rewitemcount3          int     `json:"RewItemCount3"`
	Rewitemcount4          int     `json:"RewItemCount4"`
	Rewrepfaction1         int     `json:"RewRepFaction1"`
	Rewrepfaction2         int     `json:"RewRepFaction2"`
	Rewrepfaction3         int     `json:"RewRepFaction3"`
	Rewrepfaction4         int     `json:"RewRepFaction4"`
	Rewrepfaction5         int     `json:"RewRepFaction5"`
	Rewrepvalue1           int     `json:"RewRepValue1"`
	Rewrepvalue2           int     `json:"RewRepValue2"`
	Rewrepvalue3           int     `json:"RewRepValue3"`
	Rewrepvalue4           int     `json:"RewRepValue4"`
	Rewrepvalue5           int     `json:"RewRepValue5"`
	Rewxp                  int     `json:"RewXP"`
	Reworreqmoney          int     `json:"RewOrReqMoney"`
	Rewmoneymaxlevel       int     `json:"RewMoneyMaxLevel"`
	Rewspell               int     `json:"RewSpell"`
	Rewspellcast           int     `json:"RewSpellCast"`
	Rewmailtemplateid      int     `json:"RewMailTemplateId"`
	Rewmaildelaysecs       int     `json:"RewMailDelaySecs"`
	Rewmailmoney           int     `json:"RewMailMoney"`
	Pointmapid             int     `json:"PointMapId"`
	Pointx                 float64 `json:"PointX"`
	Pointy                 float64 `json:"PointY"`
	Pointopt               int     `json:"PointOpt"`
	Detailsemote1          int     `json:"DetailsEmote1"`
	Detailsemote2          int     `json:"DetailsEmote2"`
	Detailsemote3          int     `json:"DetailsEmote3"`
	Detailsemote4          int     `json:"DetailsEmote4"`
	Detailsemotedelay1     int     `json:"DetailsEmoteDelay1"`
	Detailsemotedelay2     int     `json:"DetailsEmoteDelay2"`
	Detailsemotedelay3     int     `json:"DetailsEmoteDelay3"`
	Detailsemotedelay4     int     `json:"DetailsEmoteDelay4"`
	Incompleteemote        int     `json:"IncompleteEmote"`
	Completeemote          int     `json:"CompleteEmote"`
	Offerrewardemote1      int     `json:"OfferRewardEmote1"`
	Offerrewardemote2      int     `json:"OfferRewardEmote2"`
	Offerrewardemote3      int     `json:"OfferRewardEmote3"`
	Offerrewardemote4      int     `json:"OfferRewardEmote4"`
	Offerrewardemotedelay1 int     `json:"OfferRewardEmoteDelay1"`
	Offerrewardemotedelay2 int     `json:"OfferRewardEmoteDelay2"`
	Offerrewardemotedelay3 int     `json:"OfferRewardEmoteDelay3"`
	Offerrewardemotedelay4 int     `json:"OfferRewardEmoteDelay4"`
	Startscript            int     `json:"StartScript"`
	Completescript         int     `json:"CompleteScript"`
}

type SpellTemplateFull struct {
	Entry                         int     `json:"entry"`
	School                        int     `json:"school"`
	Category                      int     `json:"category"`
	Castui                        int     `json:"castUI"`
	Dispel                        int     `json:"dispel"`
	Mechanic                      int     `json:"mechanic"`
	Attributes                    int     `json:"attributes"`
	Attributesex                  int     `json:"attributesEx"`
	Attributesex2                 int     `json:"attributesEx2"`
	Attributesex3                 int     `json:"attributesEx3"`
	Attributesex4                 int     `json:"attributesEx4"`
	Stances                       int     `json:"stances"`
	Stancesnot                    int     `json:"stancesNot"`
	Targets                       int     `json:"targets"`
	Targetcreaturetype            int     `json:"targetCreatureType"`
	Requiresspellfocus            int     `json:"requiresSpellFocus"`
	Casteraurastate               int     `json:"casterAuraState"`
	Targetaurastate               int     `json:"targetAuraState"`
	Castingtimeindex              int     `json:"castingTimeIndex"`
	Recoverytime                  int     `json:"recoveryTime"`
	Categoryrecoverytime          int     `json:"categoryRecoveryTime"`
	Interruptflags                int     `json:"interruptFlags"`
	Aurainterruptflags            int     `json:"auraInterruptFlags"`
	Channelinterruptflags         int     `json:"channelInterruptFlags"`
	Procflags                     int     `json:"procFlags"`
	Procchance                    int     `json:"procChance"`
	Proccharges                   int     `json:"procCharges"`
	Maxlevel                      int     `json:"maxLevel"`
	Baselevel                     int     `json:"baseLevel"`
	Spelllevel                    int     `json:"spellLevel"`
	Durationindex                 int     `json:"durationIndex"`
	Powertype                     int     `json:"powerType"`
	Manacost                      int     `json:"manaCost"`
	Mancostperlevel               int     `json:"manCostPerLevel"`
	Manapersecond                 int     `json:"manaPerSecond"`
	Manapersecondperlevel         int     `json:"manaPerSecondPerLevel"`
	Rangeindex                    int     `json:"rangeIndex"`
	Speed                         float64 `json:"speed"`
	Modelnextspell                int     `json:"modelNextSpell"`
	Stackamount                   int     `json:"stackAmount"`
	Totem1                        int     `json:"totem1"`
	Totem2                        int     `json:"totem2"`
	Reagent1                      int     `json:"reagent1"`
	Reagent2                      int     `json:"reagent2"`
	Reagent3                      int     `json:"reagent3"`
	Reagent4                      int     `json:"reagent4"`
	Reagent5                      int     `json:"reagent5"`
	Reagent6                      int     `json:"reagent6"`
	Reagent7                      int     `json:"reagent7"`
	Reagent8                      int     `json:"reagent8"`
	Reagentcount1                 int     `json:"reagentCount1"`
	Reagentcount2                 int     `json:"reagentCount2"`
	Reagentcount3                 int     `json:"reagentCount3"`
	Reagentcount4                 int     `json:"reagentCount4"`
	Reagentcount5                 int     `json:"reagentCount5"`
	Reagentcount6                 int     `json:"reagentCount6"`
	Reagentcount7                 int     `json:"reagentCount7"`
	Reagentcount8                 int     `json:"reagentCount8"`
	Equippeditemclass             int     `json:"equippedItemClass"`
	Equippeditemsubclassmask      int     `json:"equippedItemSubClassMask"`
	Equippediteminventorytypemask int     `json:"equippedItemInventoryTypeMask"`
	Effect1                       int     `json:"effect1"`
	Effect2                       int     `json:"effect2"`
	Effect3                       int     `json:"effect3"`
	Effectdiesides1               int     `json:"effectDieSides1"`
	Effectdiesides2               int     `json:"effectDieSides2"`
	Effectdiesides3               int     `json:"effectDieSides3"`
	Effectbasedice1               int     `json:"effectBaseDice1"`
	Effectbasedice2               int     `json:"effectBaseDice2"`
	Effectbasedice3               int     `json:"effectBaseDice3"`
	Effectdiceperlevel1           float64 `json:"effectDicePerLevel1"`
	Effectdiceperlevel2           float64 `json:"effectDicePerLevel2"`
	Effectdiceperlevel3           float64 `json:"effectDicePerLevel3"`
	Effectrealpointsperlevel1     float64 `json:"effectRealPointsPerLevel1"`
	Effectrealpointsperlevel2     float64 `json:"effectRealPointsPerLevel2"`
	Effectrealpointsperlevel3     float64 `json:"effectRealPointsPerLevel3"`
	Effectbasepoints1             int     `json:"effectBasePoints1"`
	Effectbasepoints2             int     `json:"effectBasePoints2"`
	Effectbasepoints3             int     `json:"effectBasePoints3"`
	Effectbonuscoefficient1       float64 `json:"effectBonusCoefficient1"`
	Effectbonuscoefficient2       float64 `json:"effectBonusCoefficient2"`
	Effectbonuscoefficient3       float64 `json:"effectBonusCoefficient3"`
	Effectmechanic1               int     `json:"effectMechanic1"`
	Effectmechanic2               int     `json:"effectMechanic2"`
	Effectmechanic3               int     `json:"effectMechanic3"`
	Effectimplicittargeta1        int     `json:"effectImplicitTargetA1"`
	Effectimplicittargeta2        int     `json:"effectImplicitTargetA2"`
	Effectimplicittargeta3        int     `json:"effectImplicitTargetA3"`
	Effectimplicittargetb1        int     `json:"effectImplicitTargetB1"`
	Effectimplicittargetb2        int     `json:"effectImplicitTargetB2"`
	Effectimplicittargetb3        int     `json:"effectImplicitTargetB3"`
	Effectradiusindex1            int     `json:"effectRadiusIndex1"`
	Effectradiusindex2            int     `json:"effectRadiusIndex2"`
	Effectradiusindex3            int     `json:"effectRadiusIndex3"`
	Effectapplyauraname1          int     `json:"effectApplyAuraName1"`
	Effectapplyauraname2          int     `json:"effectApplyAuraName2"`
	Effectapplyauraname3          int     `json:"effectApplyAuraName3"`
	Effectamplitude1              int     `json:"effectAmplitude1"`
	Effectamplitude2              int     `json:"effectAmplitude2"`
	Effectamplitude3              int     `json:"effectAmplitude3"`
	Effectmultiplevalue1          float64 `json:"effectMultipleValue1"`
	Effectmultiplevalue2          float64 `json:"effectMultipleValue2"`
	Effectmultiplevalue3          float64 `json:"effectMultipleValue3"`
	Effectchaintarget1            int     `json:"effectChainTarget1"`
	Effectchaintarget2            int     `json:"effectChainTarget2"`
	Effectchaintarget3            int     `json:"effectChainTarget3"`
	Effectitemtype1               int     `json:"effectItemType1"`
	Effectitemtype2               int     `json:"effectItemType2"`
	Effectitemtype3               int     `json:"effectItemType3"`
	Effectmiscvalue1              int     `json:"effectMiscValue1"`
	Effectmiscvalue2              int     `json:"effectMiscValue2"`
	Effectmiscvalue3              int     `json:"effectMiscValue3"`
	Effecttriggerspell1           int     `json:"effectTriggerSpell1"`
	Effecttriggerspell2           int     `json:"effectTriggerSpell2"`
	Effecttriggerspell3           int     `json:"effectTriggerSpell3"`
	Effectpointspercombopoint1    float64 `json:"effectPointsPerComboPoint1"`
	Effectpointspercombopoint2    float64 `json:"effectPointsPerComboPoint2"`
	Effectpointspercombopoint3    float64 `json:"effectPointsPerComboPoint3"`
	Spellvisual1                  int     `json:"spellVisual1"`
	Spellvisual2                  int     `json:"spellVisual2"`
	Spelliconid                   int     `json:"spellIconId"`
	Activeiconid                  int     `json:"activeIconId"`
	Spellpriority                 int     `json:"spellPriority"`
	Name                          string  `json:"name"`
	Nameflags                     int     `json:"nameFlags"`
	Namesubtext                   string  `json:"nameSubtext"`
	Namesubtextflags              int     `json:"nameSubtextFlags"`
	Description                   string  `json:"description"`
	Descriptionflags              int     `json:"descriptionFlags"`
	Auradescription               string  `json:"auraDescription"`
	Auradescriptionflags          int     `json:"auraDescriptionFlags"`
	Manacostpercentage            int     `json:"manaCostPercentage"`
	Startrecoverycategory         int     `json:"startRecoveryCategory"`
	Startrecoverytime             int     `json:"startRecoveryTime"`
	Mintargetlevel                int     `json:"minTargetLevel"`
	Maxtargetlevel                int     `json:"maxTargetLevel"`
	Spellfamilyname               int     `json:"spellFamilyName"`
	Spellfamilyflags              int64   `json:"spellFamilyFlags"`
	Maxaffectedtargets            int     `json:"maxAffectedTargets"`
	Dmgclass                      int     `json:"dmgClass"`
	Preventiontype                int     `json:"preventionType"`
	Stancebarorder                int     `json:"stanceBarOrder"`
	Dmgmultiplier1                float64 `json:"dmgMultiplier1"`
	Dmgmultiplier2                float64 `json:"dmgMultiplier2"`
	Dmgmultiplier3                float64 `json:"dmgMultiplier3"`
	Minfactionid                  int     `json:"minFactionId"`
	Minreputation                 int     `json:"minReputation"`
	Requiredauravision            int     `json:"requiredAuraVision"`
	Customflags                   int     `json:"customFlags"`
}

type GameobjectTemplateFull struct {
	Entry        int     `json:"entry"`
	Type         int     `json:"type"`
	Displayid    int     `json:"displayId"`
	Name         string  `json:"name"`
	Faction      int     `json:"faction"`
	Flags        int     `json:"flags"`
	Size         float64 `json:"size"`
	Data0        int     `json:"data0"`
	Data1        int     `json:"data1"`
	Data2        int     `json:"data2"`
	Data3        int     `json:"data3"`
	Data4        int     `json:"data4"`
	Data5        int     `json:"data5"`
	Data6        int     `json:"data6"`
	Data7        int     `json:"data7"`
	Data8        int     `json:"data8"`
	Data9        int     `json:"data9"`
	Data10       int     `json:"data10"`
	Data11       int     `json:"data11"`
	Data12       int     `json:"data12"`
	Data13       int     `json:"data13"`
	Data14       int     `json:"data14"`
	Data15       int     `json:"data15"`
	Data16       int     `json:"data16"`
	Data17       int     `json:"data17"`
	Data18       int     `json:"data18"`
	Data19       int     `json:"data19"`
	Data20       int     `json:"data20"`
	Data21       int     `json:"data21"`
	Data22       int     `json:"data22"`
	Data23       int     `json:"data23"`
	Mingold      int     `json:"mingold"`
	Maxgold      int     `json:"maxgold"`
	PhaseQuestId int     `json:"phase_quest_id"`
	ScriptName   string  `json:"script_name"`
}
