// Package schema contains database schema definitions
package schema

// CoreSchema returns the SQL statements for core tables
// Note: Main data tables (item_template, creature_template, quest_template, spell_template, gameobject_template)
// are now generated by GeneratedSchema() for 1:1 MySQL compatibility
func CoreSchema() string {
	return `
	-- Item Sets (still needed, not in MySQL 1:1)
	CREATE TABLE IF NOT EXISTS itemsets (
		itemset_id INTEGER PRIMARY KEY,
		name TEXT NOT NULL,
		item1 INTEGER DEFAULT 0, item2 INTEGER DEFAULT 0, item3 INTEGER DEFAULT 0,
		item4 INTEGER DEFAULT 0, item5 INTEGER DEFAULT 0, item6 INTEGER DEFAULT 0,
		item7 INTEGER DEFAULT 0, item8 INTEGER DEFAULT 0, item9 INTEGER DEFAULT 0,
		item10 INTEGER DEFAULT 0,
		skill_id INTEGER DEFAULT 0,
		skill_level INTEGER DEFAULT 0,
		bonus1 INTEGER DEFAULT 0, bonus2 INTEGER DEFAULT 0, bonus3 INTEGER DEFAULT 0,
		bonus4 INTEGER DEFAULT 0, bonus5 INTEGER DEFAULT 0, bonus6 INTEGER DEFAULT 0,
		bonus7 INTEGER DEFAULT 0, bonus8 INTEGER DEFAULT 0,
		spell1 INTEGER DEFAULT 0, spell2 INTEGER DEFAULT 0, spell3 INTEGER DEFAULT 0,
		spell4 INTEGER DEFAULT 0, spell5 INTEGER DEFAULT 0, spell6 INTEGER DEFAULT 0,
		spell7 INTEGER DEFAULT 0, spell8 INTEGER DEFAULT 0
	);

	-- Quest Categories
	CREATE TABLE IF NOT EXISTS quest_categories (
		id INTEGER PRIMARY KEY,
		name TEXT NOT NULL
	);

	-- Quest Category Groups
	CREATE TABLE IF NOT EXISTS quest_category_groups (
		id INTEGER PRIMARY KEY,
		name TEXT NOT NULL
	);

	-- Quest Categories Enhanced
	CREATE TABLE IF NOT EXISTS quest_categories_enhanced (
		id INTEGER PRIMARY KEY,
		group_id INTEGER DEFAULT 0,
		name TEXT NOT NULL,
		quest_count INTEGER DEFAULT 0
	);

	-- NPC Quest Start/End (Table names match MySQL)
	CREATE TABLE IF NOT EXISTS creature_questrelation (
		id INTEGER,
		quest INTEGER,
		PRIMARY KEY (id, quest)
	);

	CREATE TABLE IF NOT EXISTS creature_involvedrelation (
		id INTEGER,
		quest INTEGER,
		PRIMARY KEY (id, quest)
	);

	-- GameObject Quest Start/End
	CREATE TABLE IF NOT EXISTS gameobject_questrelation (
		id INTEGER,
		quest INTEGER,
		PRIMARY KEY (id, quest)
	);

	CREATE TABLE IF NOT EXISTS gameobject_involvedrelation (
		id INTEGER,
		quest INTEGER,
		PRIMARY KEY (id, quest)
	);

	-- Spell Durations
	CREATE TABLE IF NOT EXISTS spell_durations (
		id INTEGER PRIMARY KEY,
		duration_base INTEGER DEFAULT 0,
		duration_per_level INTEGER DEFAULT 0,
		max_duration INTEGER DEFAULT 0
	);

	-- Spell Range
	CREATE TABLE IF NOT EXISTS spell_range (
		id INTEGER PRIMARY KEY,
		range_min REAL DEFAULT 0,
		range_max REAL DEFAULT 0,
		name TEXT DEFAULT ''
	);

	-- Spell Radius
	CREATE TABLE IF NOT EXISTS spell_radius (
		id INTEGER PRIMARY KEY,
		radius_base REAL DEFAULT 0,
		radius_per_level REAL DEFAULT 0,
		radius_max REAL DEFAULT 0
	);

	-- Spell Cast Times
	CREATE TABLE IF NOT EXISTS spell_cast_times (
		id INTEGER PRIMARY KEY,
		base INTEGER DEFAULT 0,
		per_level INTEGER DEFAULT 0,
		minimum INTEGER DEFAULT 0
	);

	-- Spell Skill Categories
	CREATE TABLE IF NOT EXISTS spell_skill_categories (
		id INTEGER PRIMARY KEY,
		name TEXT NOT NULL
	);

	-- Spell Skills
	CREATE TABLE IF NOT EXISTS spell_skills (
		id INTEGER PRIMARY KEY,
		category_id INTEGER DEFAULT 0,
		name TEXT NOT NULL
	);

	-- Spell Skill Spells
	CREATE TABLE IF NOT EXISTS spell_skill_spells (
		skill_id INTEGER,
		spell_id INTEGER,
		PRIMARY KEY (skill_id, spell_id)
	);

	-- Spell Icons (maps spellIconId to icon file name)
	CREATE TABLE IF NOT EXISTS spell_icons (
		id INTEGER PRIMARY KEY,
		icon_name TEXT NOT NULL
	);

	-- Loot Tables (column names match MySQL)
	CREATE TABLE IF NOT EXISTS creature_loot_template (
		entry INTEGER,
		item INTEGER,
		ChanceOrQuestChance REAL DEFAULT 0,
		groupid INTEGER DEFAULT 0,
		mincountOrRef INTEGER DEFAULT 1,
		maxcount INTEGER DEFAULT 1,
		PRIMARY KEY (entry, item)
	);

	CREATE TABLE IF NOT EXISTS reference_loot_template (
		entry INTEGER,
		item INTEGER,
		ChanceOrQuestChance REAL DEFAULT 0,
		groupid INTEGER DEFAULT 0,
		mincountOrRef INTEGER DEFAULT 1,
		maxcount INTEGER DEFAULT 1,
		PRIMARY KEY (entry, item)
	);

	CREATE TABLE IF NOT EXISTS gameobject_loot_template (
		entry INTEGER,
		item INTEGER,
		ChanceOrQuestChance REAL DEFAULT 0,
		groupid INTEGER DEFAULT 0,
		mincountOrRef INTEGER DEFAULT 1,
		maxcount INTEGER DEFAULT 1,
		PRIMARY KEY (entry, item)
	);

	CREATE TABLE IF NOT EXISTS item_loot_template (
		entry INTEGER,
		item INTEGER,
		ChanceOrQuestChance REAL DEFAULT 0,
		groupid INTEGER DEFAULT 0,
		mincountOrRef INTEGER DEFAULT 1,
		maxcount INTEGER DEFAULT 1,
		PRIMARY KEY (entry, item)
	);

	CREATE TABLE IF NOT EXISTS disenchant_loot_template (
		entry INTEGER,
		item INTEGER,
		ChanceOrQuestChance REAL DEFAULT 0,
		groupid INTEGER DEFAULT 0,
		mincountOrRef INTEGER DEFAULT 1,
		maxcount INTEGER DEFAULT 1,
		PRIMARY KEY (entry, item)
	);

	CREATE INDEX IF NOT EXISTS idx_creature_loot_item ON creature_loot_template(item);
	CREATE INDEX IF NOT EXISTS idx_reference_loot_entry ON reference_loot_template(entry);

	-- Locks (for object requirements)
	CREATE TABLE IF NOT EXISTS locks (
		id INTEGER PRIMARY KEY,
		type1 INTEGER DEFAULT 0, type2 INTEGER DEFAULT 0, type3 INTEGER DEFAULT 0,
		type4 INTEGER DEFAULT 0, type5 INTEGER DEFAULT 0,
		prop1 INTEGER DEFAULT 0, prop2 INTEGER DEFAULT 0, prop3 INTEGER DEFAULT 0,
		prop4 INTEGER DEFAULT 0, prop5 INTEGER DEFAULT 0,
		req1 INTEGER DEFAULT 0, req2 INTEGER DEFAULT 0, req3 INTEGER DEFAULT 0,
		req4 INTEGER DEFAULT 0, req5 INTEGER DEFAULT 0
	);

	CREATE INDEX IF NOT EXISTS idx_gameobject_template_name ON gameobject_template(name);
	CREATE INDEX IF NOT EXISTS idx_gameobject_template_type ON gameobject_template(type);

	-- Factions
	CREATE TABLE IF NOT EXISTS factions (
		id INTEGER PRIMARY KEY,
		name TEXT NOT NULL,
		description TEXT,
		side INTEGER DEFAULT 0,
		category_id INTEGER DEFAULT 0
	);

	CREATE INDEX IF NOT EXISTS idx_factions_name ON factions(name);

	-- Categories (for general categorization)
	CREATE TABLE IF NOT EXISTS categories (
		id INTEGER PRIMARY KEY AUTOINCREMENT,
		key TEXT UNIQUE NOT NULL,
		name TEXT NOT NULL,
		parent_id INTEGER,
		type TEXT,
		sort_order INTEGER DEFAULT 0
	);

	CREATE TABLE IF NOT EXISTS category_items (
		category_id INTEGER,
		item_id INTEGER,
		drop_rate TEXT,
		sort_order INTEGER DEFAULT 0,
		PRIMARY KEY (category_id, item_id)
	);

	-- Creature Metadata (Scraped info)
	CREATE TABLE IF NOT EXISTS creature_metadata (
		entry INTEGER PRIMARY KEY,
		map_url TEXT,
		infobox_json TEXT
	);

	-- Indexes for 1:1 tables (created after GeneratedSchema)
	CREATE INDEX IF NOT EXISTS idx_item_template_name ON item_template(name);
	CREATE INDEX IF NOT EXISTS idx_item_template_class ON item_template(class);
	CREATE INDEX IF NOT EXISTS idx_item_template_quality ON item_template(quality);
	CREATE INDEX IF NOT EXISTS idx_item_template_display_id ON item_template(display_id);
	CREATE INDEX IF NOT EXISTS idx_creature_template_name ON creature_template(name);
	CREATE INDEX IF NOT EXISTS idx_quest_template_title ON quest_template(Title);
	CREATE INDEX IF NOT EXISTS idx_spell_template_name ON spell_template(name);
	CREATE INDEX IF NOT EXISTS idx_spell_template_icon_id ON spell_template(spellIconId);

	-- Aowow Zones (for coordinate conversion)
	CREATE TABLE IF NOT EXISTS aowow_zones (
		mapID INTEGER,
		zoneID INTEGER,
		name_loc0 TEXT,
		x_min REAL,
		x_max REAL,
		y_min REAL,
		y_max REAL,
		areatableID INTEGER,
		PRIMARY KEY (mapID, zoneID, x_min, x_max, y_min, y_max)
	);

	-- Creature Spawns (Synced from MySQL)
	CREATE TABLE IF NOT EXISTS creature_spawn (
		id INTEGER PRIMARY KEY AUTOINCREMENT,
		creature_entry INTEGER,
		map_id INTEGER,
		zone_id INTEGER,
		zone_name TEXT,
		position_x REAL,
		position_y REAL,
		position_z REAL,
		UNIQUE(creature_entry, map_id, position_x, position_y)
	);
	CREATE INDEX IF NOT EXISTS idx_creature_spawn_entry ON creature_spawn(creature_entry);
	`
}
