package schema

import (
	"database/sql"
)

func GeneratedSchema() string {
	return `
    CREATE TABLE IF NOT EXISTS item_template (
        entry INTEGER DEFAULT 0,
        class INTEGER DEFAULT 0,
        subclass INTEGER DEFAULT 0,
        name TEXT DEFAULT '',
        description TEXT DEFAULT '',
        display_id INTEGER DEFAULT 0,
        quality INTEGER DEFAULT 0,
        flags INTEGER DEFAULT 0,
        buy_count INTEGER DEFAULT 1,
        buy_price INTEGER DEFAULT 0,
        sell_price INTEGER DEFAULT 0,
        inventory_type INTEGER DEFAULT 0,
        allowable_class INTEGER DEFAULT -1,
        allowable_race INTEGER DEFAULT -1,
        item_level INTEGER DEFAULT 0,
        required_level INTEGER DEFAULT 0,
        required_skill INTEGER DEFAULT 0,
        required_skill_rank INTEGER DEFAULT 0,
        required_spell INTEGER DEFAULT 0,
        required_honor_rank INTEGER DEFAULT 0,
        required_city_rank INTEGER DEFAULT 0,
        required_reputation_faction INTEGER DEFAULT 0,
        required_reputation_rank INTEGER DEFAULT 0,
        max_count INTEGER DEFAULT 0,
        stackable INTEGER DEFAULT 1,
        container_slots INTEGER DEFAULT 0,
        stat_type1 INTEGER DEFAULT 0,
        stat_value1 INTEGER DEFAULT 0,
        stat_type2 INTEGER DEFAULT 0,
        stat_value2 INTEGER DEFAULT 0,
        stat_type3 INTEGER DEFAULT 0,
        stat_value3 INTEGER DEFAULT 0,
        stat_type4 INTEGER DEFAULT 0,
        stat_value4 INTEGER DEFAULT 0,
        stat_type5 INTEGER DEFAULT 0,
        stat_value5 INTEGER DEFAULT 0,
        stat_type6 INTEGER DEFAULT 0,
        stat_value6 INTEGER DEFAULT 0,
        stat_type7 INTEGER DEFAULT 0,
        stat_value7 INTEGER DEFAULT 0,
        stat_type8 INTEGER DEFAULT 0,
        stat_value8 INTEGER DEFAULT 0,
        stat_type9 INTEGER DEFAULT 0,
        stat_value9 INTEGER DEFAULT 0,
        stat_type10 INTEGER DEFAULT 0,
        stat_value10 INTEGER DEFAULT 0,
        delay INTEGER DEFAULT 1000,
        range_mod REAL DEFAULT 0,
        ammo_type INTEGER DEFAULT 0,
        dmg_min1 REAL DEFAULT 0,
        dmg_max1 REAL DEFAULT 0,
        dmg_type1 INTEGER DEFAULT 0,
        dmg_min2 REAL DEFAULT 0,
        dmg_max2 REAL DEFAULT 0,
        dmg_type2 INTEGER DEFAULT 0,
        dmg_min3 REAL DEFAULT 0,
        dmg_max3 REAL DEFAULT 0,
        dmg_type3 INTEGER DEFAULT 0,
        dmg_min4 REAL DEFAULT 0,
        dmg_max4 REAL DEFAULT 0,
        dmg_type4 INTEGER DEFAULT 0,
        dmg_min5 REAL DEFAULT 0,
        dmg_max5 REAL DEFAULT 0,
        dmg_type5 INTEGER DEFAULT 0,
        block INTEGER DEFAULT 0,
        armor INTEGER DEFAULT 0,
        holy_res INTEGER DEFAULT 0,
        fire_res INTEGER DEFAULT 0,
        nature_res INTEGER DEFAULT 0,
        frost_res INTEGER DEFAULT 0,
        shadow_res INTEGER DEFAULT 0,
        arcane_res INTEGER DEFAULT 0,
        spellid_1 INTEGER DEFAULT 0,
        spelltrigger_1 INTEGER DEFAULT 0,
        spellcharges_1 INTEGER DEFAULT 0,
        spellppmrate_1 REAL DEFAULT 0,
        spellcooldown_1 INTEGER DEFAULT -1,
        spellcategory_1 INTEGER DEFAULT 0,
        spellcategorycooldown_1 INTEGER DEFAULT -1,
        spellid_2 INTEGER DEFAULT 0,
        spelltrigger_2 INTEGER DEFAULT 0,
        spellcharges_2 INTEGER DEFAULT 0,
        spellppmrate_2 REAL DEFAULT 0,
        spellcooldown_2 INTEGER DEFAULT -1,
        spellcategory_2 INTEGER DEFAULT 0,
        spellcategorycooldown_2 INTEGER DEFAULT -1,
        spellid_3 INTEGER DEFAULT 0,
        spelltrigger_3 INTEGER DEFAULT 0,
        spellcharges_3 INTEGER DEFAULT 0,
        spellppmrate_3 REAL DEFAULT 0,
        spellcooldown_3 INTEGER DEFAULT -1,
        spellcategory_3 INTEGER DEFAULT 0,
        spellcategorycooldown_3 INTEGER DEFAULT -1,
        spellid_4 INTEGER DEFAULT 0,
        spelltrigger_4 INTEGER DEFAULT 0,
        spellcharges_4 INTEGER DEFAULT 0,
        spellppmrate_4 REAL DEFAULT 0,
        spellcooldown_4 INTEGER DEFAULT -1,
        spellcategory_4 INTEGER DEFAULT 0,
        spellcategorycooldown_4 INTEGER DEFAULT -1,
        spellid_5 INTEGER DEFAULT 0,
        spelltrigger_5 INTEGER DEFAULT 0,
        spellcharges_5 INTEGER DEFAULT 0,
        spellppmrate_5 REAL DEFAULT 0,
        spellcooldown_5 INTEGER DEFAULT -1,
        spellcategory_5 INTEGER DEFAULT 0,
        spellcategorycooldown_5 INTEGER DEFAULT -1,
        bonding INTEGER DEFAULT 0,
        page_text INTEGER DEFAULT 0,
        page_language INTEGER DEFAULT 0,
        page_material INTEGER DEFAULT 0,
        start_quest INTEGER DEFAULT 0,
        lock_id INTEGER DEFAULT 0,
        material INTEGER DEFAULT 0,
        sheath INTEGER DEFAULT 0,
        random_property INTEGER DEFAULT 0,
        set_id INTEGER DEFAULT 0,
        max_durability INTEGER DEFAULT 0,
        area_bound INTEGER DEFAULT 0,
        map_bound INTEGER DEFAULT 0,
        duration INTEGER DEFAULT 0,
        bag_family INTEGER DEFAULT 0,
        disenchant_id INTEGER DEFAULT 0,
        food_type INTEGER DEFAULT 0,
        min_money_loot INTEGER DEFAULT 0,
        max_money_loot INTEGER DEFAULT 0,
        wrapped_gift INTEGER DEFAULT 0,
        extra_flags INTEGER DEFAULT 0,
        other_team_entry INTEGER DEFAULT 1,
        script_name TEXT,
        PRIMARY KEY (entry)
    );

    CREATE TABLE IF NOT EXISTS item_display_info (
        ID INTEGER PRIMARY KEY,
        icon TEXT DEFAULT ''
    );


    CREATE TABLE IF NOT EXISTS creature_template (
        entry INTEGER DEFAULT 0,
        display_id1 INTEGER DEFAULT 0,
        display_id2 INTEGER DEFAULT 0,
        display_id3 INTEGER DEFAULT 0,
        display_id4 INTEGER DEFAULT 0,
        mount_display_id INTEGER DEFAULT 0,
        name TEXT DEFAULT '0',
        subname TEXT,
        gossip_menu_id INTEGER DEFAULT 0,
        level_min INTEGER DEFAULT 1,
        level_max INTEGER DEFAULT 1,
        health_min INTEGER DEFAULT 0,
        health_max INTEGER DEFAULT 0,
        mana_min INTEGER DEFAULT 0,
        mana_max INTEGER DEFAULT 0,
        armor INTEGER DEFAULT 0,
        faction INTEGER DEFAULT 0,
        npc_flags INTEGER DEFAULT 0,
        speed_walk REAL DEFAULT 1,
        speed_run REAL DEFAULT 1.14286,
        scale REAL DEFAULT 1,
        detection_range REAL DEFAULT 20,
        call_for_help_range REAL DEFAULT 5,
        leash_range REAL DEFAULT 0,
        rank INTEGER DEFAULT 0,
        xp_multiplier REAL DEFAULT 1,
        dmg_min REAL DEFAULT 0,
        dmg_max REAL DEFAULT 0,
        dmg_school INTEGER DEFAULT 0,
        attack_power INTEGER DEFAULT 0,
        dmg_multiplier REAL DEFAULT 1,
        base_attack_time INTEGER DEFAULT 0,
        ranged_attack_time INTEGER DEFAULT 0,
        unit_class INTEGER DEFAULT 0,
        unit_flags INTEGER DEFAULT 0,
        dynamic_flags INTEGER DEFAULT 0,
        beast_family INTEGER DEFAULT 0,
        trainer_type INTEGER DEFAULT 0,
        trainer_spell INTEGER DEFAULT 0,
        trainer_class INTEGER DEFAULT 0,
        trainer_race INTEGER DEFAULT 0,
        ranged_dmg_min REAL DEFAULT 0,
        ranged_dmg_max REAL DEFAULT 0,
        ranged_attack_power INTEGER DEFAULT 0,
        type INTEGER DEFAULT 0,
        type_flags INTEGER DEFAULT 0,
        loot_id INTEGER DEFAULT 0,
        pickpocket_loot_id INTEGER DEFAULT 0,
        skinning_loot_id INTEGER DEFAULT 0,
        holy_res INTEGER DEFAULT 0,
        fire_res INTEGER DEFAULT 0,
        nature_res INTEGER DEFAULT 0,
        frost_res INTEGER DEFAULT 0,
        shadow_res INTEGER DEFAULT 0,
        arcane_res INTEGER DEFAULT 0,
        spell_id1 INTEGER DEFAULT 0,
        spell_id2 INTEGER DEFAULT 0,
        spell_id3 INTEGER DEFAULT 0,
        spell_id4 INTEGER DEFAULT 0,
        spell_list_id INTEGER DEFAULT 0,
        pet_spell_list_id INTEGER DEFAULT 0,
        spawn_spell_id INTEGER DEFAULT 0,
        auras TEXT,
        gold_min INTEGER DEFAULT 0,
        gold_max INTEGER DEFAULT 0,
        ai_name TEXT DEFAULT '',
        movement_type INTEGER DEFAULT 0,
        inhabit_type INTEGER DEFAULT 3,
        civilian INTEGER DEFAULT 0,
        racial_leader INTEGER DEFAULT 0,
        regeneration INTEGER DEFAULT 3,
        equipment_id INTEGER DEFAULT 0,
        trainer_id INTEGER DEFAULT 0,
        vendor_id INTEGER DEFAULT 0,
        mechanic_immune_mask INTEGER DEFAULT 0,
        school_immune_mask INTEGER DEFAULT 0,
        immunity_flags INTEGER DEFAULT 0,
        flags_extra INTEGER DEFAULT 0,
        phase_quest_id INTEGER DEFAULT 0,
        script_name TEXT DEFAULT '',
        PRIMARY KEY (entry)
    );

    CREATE TABLE IF NOT EXISTS quest_template (
        entry INTEGER DEFAULT 0,
        Method INTEGER DEFAULT 2,
        ZoneOrSort INTEGER DEFAULT 0,
        MinLevel INTEGER DEFAULT 0,
        MaxLevel INTEGER DEFAULT 0,
        QuestLevel INTEGER DEFAULT 0,
        Type INTEGER DEFAULT 0,
        RequiredClasses INTEGER DEFAULT 0,
        RequiredRaces INTEGER DEFAULT 0,
        RequiredSkill INTEGER DEFAULT 0,
        RequiredSkillValue INTEGER DEFAULT 0,
        RequiredCondition INTEGER DEFAULT 0,
        RepObjectiveFaction INTEGER DEFAULT 0,
        RepObjectiveValue INTEGER DEFAULT 0,
        RequiredMinRepFaction INTEGER DEFAULT 0,
        RequiredMinRepValue INTEGER DEFAULT 0,
        RequiredMaxRepFaction INTEGER DEFAULT 0,
        RequiredMaxRepValue INTEGER DEFAULT 0,
        SuggestedPlayers INTEGER DEFAULT 0,
        LimitTime INTEGER DEFAULT 0,
        QuestFlags INTEGER DEFAULT 0,
        SpecialFlags INTEGER DEFAULT 0,
        PrevQuestId INTEGER DEFAULT 0,
        NextQuestId INTEGER DEFAULT 0,
        ExclusiveGroup INTEGER DEFAULT 0,
        NextQuestInChain INTEGER DEFAULT 0,
        SrcItemId INTEGER DEFAULT 0,
        SrcItemCount INTEGER DEFAULT 0,
        SrcSpell INTEGER DEFAULT 0,
        Title TEXT,
        Details TEXT,
        Objectives TEXT,
        OfferRewardText TEXT,
        RequestItemsText TEXT,
        EndText TEXT,
        ObjectiveText1 TEXT,
        ObjectiveText2 TEXT,
        ObjectiveText3 TEXT,
        ObjectiveText4 TEXT,
        ReqItemId1 INTEGER DEFAULT 0,
        ReqItemId2 INTEGER DEFAULT 0,
        ReqItemId3 INTEGER DEFAULT 0,
        ReqItemId4 INTEGER DEFAULT 0,
        ReqItemCount1 INTEGER DEFAULT 0,
        ReqItemCount2 INTEGER DEFAULT 0,
        ReqItemCount3 INTEGER DEFAULT 0,
        ReqItemCount4 INTEGER DEFAULT 0,
        ReqSourceId1 INTEGER DEFAULT 0,
        ReqSourceId2 INTEGER DEFAULT 0,
        ReqSourceId3 INTEGER DEFAULT 0,
        ReqSourceId4 INTEGER DEFAULT 0,
        ReqSourceCount1 INTEGER DEFAULT 0,
        ReqSourceCount2 INTEGER DEFAULT 0,
        ReqSourceCount3 INTEGER DEFAULT 0,
        ReqSourceCount4 INTEGER DEFAULT 0,
        ReqCreatureOrGOId1 INTEGER DEFAULT 0,
        ReqCreatureOrGOId2 INTEGER DEFAULT 0,
        ReqCreatureOrGOId3 INTEGER DEFAULT 0,
        ReqCreatureOrGOId4 INTEGER DEFAULT 0,
        ReqCreatureOrGOCount1 INTEGER DEFAULT 0,
        ReqCreatureOrGOCount2 INTEGER DEFAULT 0,
        ReqCreatureOrGOCount3 INTEGER DEFAULT 0,
        ReqCreatureOrGOCount4 INTEGER DEFAULT 0,
        ReqSpellCast1 INTEGER DEFAULT 0,
        ReqSpellCast2 INTEGER DEFAULT 0,
        ReqSpellCast3 INTEGER DEFAULT 0,
        ReqSpellCast4 INTEGER DEFAULT 0,
        RewChoiceItemId1 INTEGER DEFAULT 0,
        RewChoiceItemId2 INTEGER DEFAULT 0,
        RewChoiceItemId3 INTEGER DEFAULT 0,
        RewChoiceItemId4 INTEGER DEFAULT 0,
        RewChoiceItemId5 INTEGER DEFAULT 0,
        RewChoiceItemId6 INTEGER DEFAULT 0,
        RewChoiceItemCount1 INTEGER DEFAULT 0,
        RewChoiceItemCount2 INTEGER DEFAULT 0,
        RewChoiceItemCount3 INTEGER DEFAULT 0,
        RewChoiceItemCount4 INTEGER DEFAULT 0,
        RewChoiceItemCount5 INTEGER DEFAULT 0,
        RewChoiceItemCount6 INTEGER DEFAULT 0,
        RewItemId1 INTEGER DEFAULT 0,
        RewItemId2 INTEGER DEFAULT 0,
        RewItemId3 INTEGER DEFAULT 0,
        RewItemId4 INTEGER DEFAULT 0,
        RewItemCount1 INTEGER DEFAULT 0,
        RewItemCount2 INTEGER DEFAULT 0,
        RewItemCount3 INTEGER DEFAULT 0,
        RewItemCount4 INTEGER DEFAULT 0,
        RewRepFaction1 INTEGER DEFAULT 0,
        RewRepFaction2 INTEGER DEFAULT 0,
        RewRepFaction3 INTEGER DEFAULT 0,
        RewRepFaction4 INTEGER DEFAULT 0,
        RewRepFaction5 INTEGER DEFAULT 0,
        RewRepValue1 INTEGER DEFAULT 0,
        RewRepValue2 INTEGER DEFAULT 0,
        RewRepValue3 INTEGER DEFAULT 0,
        RewRepValue4 INTEGER DEFAULT 0,
        RewRepValue5 INTEGER DEFAULT 0,
        RewXP INTEGER DEFAULT 0,
        RewOrReqMoney INTEGER DEFAULT 0,
        RewMoneyMaxLevel INTEGER DEFAULT 0,
        RewSpell INTEGER DEFAULT 0,
        RewSpellCast INTEGER DEFAULT 0,
        RewMailTemplateId INTEGER DEFAULT 0,
        RewMailDelaySecs INTEGER DEFAULT 0,
        RewMailMoney INTEGER DEFAULT 0,
        PointMapId INTEGER DEFAULT 0,
        PointX REAL DEFAULT 0,
        PointY REAL DEFAULT 0,
        PointOpt INTEGER DEFAULT 0,
        DetailsEmote1 INTEGER DEFAULT 0,
        DetailsEmote2 INTEGER DEFAULT 0,
        DetailsEmote3 INTEGER DEFAULT 0,
        DetailsEmote4 INTEGER DEFAULT 0,
        DetailsEmoteDelay1 INTEGER DEFAULT 0,
        DetailsEmoteDelay2 INTEGER DEFAULT 0,
        DetailsEmoteDelay3 INTEGER DEFAULT 0,
        DetailsEmoteDelay4 INTEGER DEFAULT 0,
        IncompleteEmote INTEGER DEFAULT 0,
        CompleteEmote INTEGER DEFAULT 0,
        OfferRewardEmote1 INTEGER DEFAULT 0,
        OfferRewardEmote2 INTEGER DEFAULT 0,
        OfferRewardEmote3 INTEGER DEFAULT 0,
        OfferRewardEmote4 INTEGER DEFAULT 0,
        OfferRewardEmoteDelay1 INTEGER DEFAULT 0,
        OfferRewardEmoteDelay2 INTEGER DEFAULT 0,
        OfferRewardEmoteDelay3 INTEGER DEFAULT 0,
        OfferRewardEmoteDelay4 INTEGER DEFAULT 0,
        StartScript INTEGER DEFAULT 0,
        CompleteScript INTEGER DEFAULT 0,
        PRIMARY KEY (entry)
    );

    CREATE TABLE IF NOT EXISTS spell_template (
        entry INTEGER DEFAULT 0,
        school INTEGER DEFAULT 0,
        category INTEGER DEFAULT 0,
        castUI INTEGER DEFAULT 0,
        dispel INTEGER DEFAULT 0,
        mechanic INTEGER DEFAULT 0,
        attributes INTEGER DEFAULT 0,
        attributesEx INTEGER DEFAULT 0,
        attributesEx2 INTEGER DEFAULT 0,
        attributesEx3 INTEGER DEFAULT 0,
        attributesEx4 INTEGER DEFAULT 0,
        stances INTEGER DEFAULT 0,
        stancesNot INTEGER DEFAULT 0,
        targets INTEGER DEFAULT 0,
        targetCreatureType INTEGER DEFAULT 0,
        requiresSpellFocus INTEGER DEFAULT 0,
        casterAuraState INTEGER DEFAULT 0,
        targetAuraState INTEGER DEFAULT 0,
        castingTimeIndex INTEGER DEFAULT 0,
        recoveryTime INTEGER DEFAULT 0,
        categoryRecoveryTime INTEGER DEFAULT 0,
        interruptFlags INTEGER DEFAULT 0,
        auraInterruptFlags INTEGER DEFAULT 0,
        channelInterruptFlags INTEGER DEFAULT 0,
        procFlags INTEGER DEFAULT 0,
        procChance INTEGER DEFAULT 0,
        procCharges INTEGER DEFAULT 0,
        maxLevel INTEGER DEFAULT 0,
        baseLevel INTEGER DEFAULT 0,
        spellLevel INTEGER DEFAULT 0,
        durationIndex INTEGER DEFAULT 0,
        powerType INTEGER DEFAULT 0,
        manaCost INTEGER DEFAULT 0,
        manCostPerLevel INTEGER DEFAULT 0,
        manaPerSecond INTEGER DEFAULT 0,
        manaPerSecondPerLevel INTEGER DEFAULT 0,
        rangeIndex INTEGER DEFAULT 0,
        speed REAL DEFAULT 0,
        modelNextSpell INTEGER DEFAULT 0,
        stackAmount INTEGER DEFAULT 0,
        totem1 INTEGER DEFAULT 0,
        totem2 INTEGER DEFAULT 0,
        reagent1 INTEGER DEFAULT 0,
        reagent2 INTEGER DEFAULT 0,
        reagent3 INTEGER DEFAULT 0,
        reagent4 INTEGER DEFAULT 0,
        reagent5 INTEGER DEFAULT 0,
        reagent6 INTEGER DEFAULT 0,
        reagent7 INTEGER DEFAULT 0,
        reagent8 INTEGER DEFAULT 0,
        reagentCount1 INTEGER DEFAULT 0,
        reagentCount2 INTEGER DEFAULT 0,
        reagentCount3 INTEGER DEFAULT 0,
        reagentCount4 INTEGER DEFAULT 0,
        reagentCount5 INTEGER DEFAULT 0,
        reagentCount6 INTEGER DEFAULT 0,
        reagentCount7 INTEGER DEFAULT 0,
        reagentCount8 INTEGER DEFAULT 0,
        equippedItemClass INTEGER DEFAULT 0,
        equippedItemSubClassMask INTEGER DEFAULT 0,
        equippedItemInventoryTypeMask INTEGER DEFAULT 0,
        effect1 INTEGER DEFAULT 0,
        effect2 INTEGER DEFAULT 0,
        effect3 INTEGER DEFAULT 0,
        effectDieSides1 INTEGER DEFAULT 0,
        effectDieSides2 INTEGER DEFAULT 0,
        effectDieSides3 INTEGER DEFAULT 0,
        effectBaseDice1 INTEGER DEFAULT 0,
        effectBaseDice2 INTEGER DEFAULT 0,
        effectBaseDice3 INTEGER DEFAULT 0,
        effectDicePerLevel1 REAL DEFAULT 0,
        effectDicePerLevel2 REAL DEFAULT 0,
        effectDicePerLevel3 REAL DEFAULT 0,
        effectRealPointsPerLevel1 REAL DEFAULT 0,
        effectRealPointsPerLevel2 REAL DEFAULT 0,
        effectRealPointsPerLevel3 REAL DEFAULT 0,
        effectBasePoints1 INTEGER DEFAULT 0,
        effectBasePoints2 INTEGER DEFAULT 0,
        effectBasePoints3 INTEGER DEFAULT 0,
        effectBonusCoefficient1 REAL DEFAULT -1,
        effectBonusCoefficient2 REAL DEFAULT -1,
        effectBonusCoefficient3 REAL DEFAULT -1,
        effectMechanic1 INTEGER DEFAULT 0,
        effectMechanic2 INTEGER DEFAULT 0,
        effectMechanic3 INTEGER DEFAULT 0,
        effectImplicitTargetA1 INTEGER DEFAULT 0,
        effectImplicitTargetA2 INTEGER DEFAULT 0,
        effectImplicitTargetA3 INTEGER DEFAULT 0,
        effectImplicitTargetB1 INTEGER DEFAULT 0,
        effectImplicitTargetB2 INTEGER DEFAULT 0,
        effectImplicitTargetB3 INTEGER DEFAULT 0,
        effectRadiusIndex1 INTEGER DEFAULT 0,
        effectRadiusIndex2 INTEGER DEFAULT 0,
        effectRadiusIndex3 INTEGER DEFAULT 0,
        effectApplyAuraName1 INTEGER DEFAULT 0,
        effectApplyAuraName2 INTEGER DEFAULT 0,
        effectApplyAuraName3 INTEGER DEFAULT 0,
        effectAmplitude1 INTEGER DEFAULT 0,
        effectAmplitude2 INTEGER DEFAULT 0,
        effectAmplitude3 INTEGER DEFAULT 0,
        effectMultipleValue1 REAL DEFAULT 0,
        effectMultipleValue2 REAL DEFAULT 0,
        effectMultipleValue3 REAL DEFAULT 0,
        effectChainTarget1 INTEGER DEFAULT 0,
        effectChainTarget2 INTEGER DEFAULT 0,
        effectChainTarget3 INTEGER DEFAULT 0,
        effectItemType1 INTEGER DEFAULT 0,
        effectItemType2 INTEGER DEFAULT 0,
        effectItemType3 INTEGER DEFAULT 0,
        effectMiscValue1 INTEGER DEFAULT 0,
        effectMiscValue2 INTEGER DEFAULT 0,
        effectMiscValue3 INTEGER DEFAULT 0,
        effectTriggerSpell1 INTEGER DEFAULT 0,
        effectTriggerSpell2 INTEGER DEFAULT 0,
        effectTriggerSpell3 INTEGER DEFAULT 0,
        effectPointsPerComboPoint1 REAL DEFAULT 0,
        effectPointsPerComboPoint2 REAL DEFAULT 0,
        effectPointsPerComboPoint3 REAL DEFAULT 0,
        spellVisual1 INTEGER DEFAULT 0,
        spellVisual2 INTEGER DEFAULT 0,
        spellIconId INTEGER DEFAULT 0,
        activeIconId INTEGER DEFAULT 0,
        spellPriority INTEGER DEFAULT 0,
        name TEXT DEFAULT '',
        nameFlags INTEGER DEFAULT 0,
        nameSubtext TEXT DEFAULT '',
        nameSubtextFlags INTEGER DEFAULT 0,
        description TEXT DEFAULT '',
        descriptionFlags INTEGER DEFAULT 0,
        auraDescription TEXT DEFAULT '',
        auraDescriptionFlags INTEGER DEFAULT 0,
        manaCostPercentage INTEGER DEFAULT 0,
        startRecoveryCategory INTEGER DEFAULT 0,
        startRecoveryTime INTEGER DEFAULT 0,
        minTargetLevel INTEGER DEFAULT 0,
        maxTargetLevel INTEGER DEFAULT 0,
        spellFamilyName INTEGER DEFAULT 0,
        spellFamilyFlags INTEGER DEFAULT 0,
        maxAffectedTargets INTEGER DEFAULT 0,
        dmgClass INTEGER DEFAULT 0,
        preventionType INTEGER DEFAULT 0,
        stanceBarOrder INTEGER DEFAULT 0,
        dmgMultiplier1 REAL DEFAULT 0,
        dmgMultiplier2 REAL DEFAULT 0,
        dmgMultiplier3 REAL DEFAULT 0,
        minFactionId INTEGER DEFAULT 0,
        minReputation INTEGER DEFAULT 0,
        requiredAuraVision INTEGER DEFAULT 0,
        customFlags INTEGER DEFAULT 0,
        iconName TEXT DEFAULT '',
        PRIMARY KEY (entry)
    );

    CREATE TABLE IF NOT EXISTS gameobject_template (
        entry INTEGER DEFAULT 0,
        type INTEGER DEFAULT 0,
        displayId INTEGER DEFAULT 0,
        name TEXT DEFAULT '',
        faction INTEGER DEFAULT 0,
        flags INTEGER DEFAULT 0,
        size REAL DEFAULT 1,
        data0 INTEGER DEFAULT 0,
        data1 INTEGER DEFAULT 0,
        data2 INTEGER DEFAULT 0,
        data3 INTEGER DEFAULT 0,
        data4 INTEGER DEFAULT 0,
        data5 INTEGER DEFAULT 0,
        data6 INTEGER DEFAULT 0,
        data7 INTEGER DEFAULT 0,
        data8 INTEGER DEFAULT 0,
        data9 INTEGER DEFAULT 0,
        data10 INTEGER DEFAULT 0,
        data11 INTEGER DEFAULT 0,
        data12 INTEGER DEFAULT 0,
        data13 INTEGER DEFAULT 0,
        data14 INTEGER DEFAULT 0,
        data15 INTEGER DEFAULT 0,
        data16 INTEGER DEFAULT 0,
        data17 INTEGER DEFAULT 0,
        data18 INTEGER DEFAULT 0,
        data19 INTEGER DEFAULT 0,
        data20 INTEGER DEFAULT 0,
        data21 INTEGER DEFAULT 0,
        data22 INTEGER DEFAULT 0,
        data23 INTEGER DEFAULT 0,
        mingold INTEGER DEFAULT 0,
        maxgold INTEGER DEFAULT 0,
        phase_quest_id INTEGER DEFAULT 0,
        script_name TEXT DEFAULT '',
        PRIMARY KEY (entry)
    );

    `
}

// MigrateV2 adds new columns for spell slots 4 and 5 to item_template
func MigrateV2(db *sql.DB) {
	// Add columns individually. Ignore errors (assuming error means column exists)
	cols := []string{
		"ALTER TABLE item_template ADD COLUMN spellid_4 INTEGER DEFAULT 0",
		"ALTER TABLE item_template ADD COLUMN spelltrigger_4 INTEGER DEFAULT 0",
		"ALTER TABLE item_template ADD COLUMN spellcharges_4 INTEGER DEFAULT 0",
		"ALTER TABLE item_template ADD COLUMN spellppmrate_4 REAL DEFAULT 0",
		"ALTER TABLE item_template ADD COLUMN spellcooldown_4 INTEGER DEFAULT -1",
		"ALTER TABLE item_template ADD COLUMN spellcategory_4 INTEGER DEFAULT 0",
		"ALTER TABLE item_template ADD COLUMN spellcategorycooldown_4 INTEGER DEFAULT -1",
		"ALTER TABLE item_template ADD COLUMN spellid_5 INTEGER DEFAULT 0",
		"ALTER TABLE item_template ADD COLUMN spelltrigger_5 INTEGER DEFAULT 0",
		"ALTER TABLE item_template ADD COLUMN spellcharges_5 INTEGER DEFAULT 0",
		"ALTER TABLE item_template ADD COLUMN spellppmrate_5 REAL DEFAULT 0",
		"ALTER TABLE item_template ADD COLUMN spellcooldown_5 INTEGER DEFAULT -1",
		"ALTER TABLE item_template ADD COLUMN spellcategory_5 INTEGER DEFAULT 0",
		"ALTER TABLE item_template ADD COLUMN spellcategorycooldown_5 INTEGER DEFAULT -1",
	}

	for _, q := range cols {
		db.Exec(q)
	}
}

// MigratePerformance adds indexes to speed up "Dropped By" and other reverse lookups
func MigratePerformance(db *sql.DB) {
	queries := []string{
		"CREATE INDEX IF NOT EXISTS idx_creature_loot_ref ON creature_loot_template(mincountOrRef)",
		"CREATE INDEX IF NOT EXISTS idx_reference_loot_item ON reference_loot_template(item)",
		"CREATE INDEX IF NOT EXISTS idx_gameobject_loot_item ON gameobject_loot_template(item)",
		"CREATE INDEX IF NOT EXISTS idx_item_loot_item ON item_loot_template(item)",
		// New Indexes for optimization
		"CREATE INDEX IF NOT EXISTS idx_creature_template_loot_id ON creature_template(loot_id)",
		"CREATE INDEX IF NOT EXISTS idx_quest_template_reward1 ON quest_template(RewItemId1)",
		"CREATE INDEX IF NOT EXISTS idx_quest_template_choice1 ON quest_template(RewChoiceItemId1)",
	}
	for _, q := range queries {
		db.Exec(q)
	}
}
