// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AdvancedSearch(arg1) {
  return window['go']['main']['App']['AdvancedSearch'](arg1);
}

export function BrowseCreaturesByType(arg1) {
  return window['go']['main']['App']['BrowseCreaturesByType'](arg1);
}

export function BrowseItemsByClass(arg1, arg2) {
  return window['go']['main']['App']['BrowseItemsByClass'](arg1, arg2);
}

export function BrowseItemsByClassAndSlot(arg1, arg2, arg3) {
  return window['go']['main']['App']['BrowseItemsByClassAndSlot'](arg1, arg2, arg3);
}

export function GetCategories() {
  return window['go']['main']['App']['GetCategories']();
}

export function GetCategoryItems(arg1) {
  return window['go']['main']['App']['GetCategoryItems'](arg1);
}

export function GetChildCategories(arg1) {
  return window['go']['main']['App']['GetChildCategories'](arg1);
}

export function GetCreatureTypes() {
  return window['go']['main']['App']['GetCreatureTypes']();
}

export function GetInstances(arg1) {
  return window['go']['main']['App']['GetInstances'](arg1);
}

export function GetItemClasses() {
  return window['go']['main']['App']['GetItemClasses']();
}

export function GetItemSetDetail(arg1) {
  return window['go']['main']['App']['GetItemSetDetail'](arg1);
}

export function GetItemSets() {
  return window['go']['main']['App']['GetItemSets']();
}

export function GetLoot(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetLoot'](arg1, arg2, arg3);
}

export function GetRootCategories() {
  return window['go']['main']['App']['GetRootCategories']();
}

export function GetTables(arg1, arg2) {
  return window['go']['main']['App']['GetTables'](arg1, arg2);
}

export function GetTooltipData(arg1) {
  return window['go']['main']['App']['GetTooltipData'](arg1);
}

export function SearchCreatures(arg1) {
  return window['go']['main']['App']['SearchCreatures'](arg1);
}

export function SearchItems(arg1) {
  return window['go']['main']['App']['SearchItems'](arg1);
}

export function WaitForReady() {
  return window['go']['main']['App']['WaitForReady']();
}
