// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {database} from '../models';
import {main} from '../models';

export function AdvancedSearch(arg1:database.SearchFilter):Promise<database.SearchResult>;

export function BrowseItemsByClass(arg1:number,arg2:number):Promise<Array<database.Item>>;

export function GetCategories():Promise<Array<string>>;

export function GetCategoryItems(arg1:number):Promise<Array<database.Item>>;

export function GetChildCategories(arg1:number):Promise<Array<database.Category>>;

export function GetInstances(arg1:string):Promise<Array<string>>;

export function GetItemClasses():Promise<Array<database.ItemClass>>;

export function GetLoot(arg1:string,arg2:string,arg3:string):Promise<main.LegacyBossLoot>;

export function GetRootCategories():Promise<Array<database.Category>>;

export function GetTables(arg1:string,arg2:string):Promise<Array<database.AtlasTable>>;

export function GetTooltipData(arg1:number):Promise<database.TooltipData>;

export function SearchItems(arg1:string):Promise<Array<database.Item>>;

export function WaitForReady():Promise<boolean>;
