// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddFavorite(arg1, arg2) {
  return window['go']['main']['App']['AddFavorite'](arg1, arg2);
}

export function AdvancedSearch(arg1) {
  return window['go']['main']['App']['AdvancedSearch'](arg1);
}

export function BrowseCreaturesByType(arg1, arg2) {
  return window['go']['main']['App']['BrowseCreaturesByType'](arg1, arg2);
}

export function BrowseCreaturesByTypePaged(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['BrowseCreaturesByTypePaged'](arg1, arg2, arg3, arg4);
}

export function BrowseItemsByClass(arg1, arg2, arg3) {
  return window['go']['main']['App']['BrowseItemsByClass'](arg1, arg2, arg3);
}

export function BrowseItemsByClassAndSlot(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['BrowseItemsByClassAndSlot'](arg1, arg2, arg3, arg4);
}

export function CheckNewItems(arg1, arg2) {
  return window['go']['main']['App']['CheckNewItems'](arg1, arg2);
}

export function CheckNewQuests(arg1, arg2) {
  return window['go']['main']['App']['CheckNewQuests'](arg1, arg2);
}

export function FetchRemoteImage(arg1, arg2, arg3) {
  return window['go']['main']['App']['FetchRemoteImage'](arg1, arg2, arg3);
}

export function FixMissingIcons(arg1, arg2) {
  return window['go']['main']['App']['FixMissingIcons'](arg1, arg2);
}

export function FixSingleItemIcon(arg1) {
  return window['go']['main']['App']['FixSingleItemIcon'](arg1);
}

export function FullSyncItems(arg1, arg2, arg3) {
  return window['go']['main']['App']['FullSyncItems'](arg1, arg2, arg3);
}

export function FullSyncNpcs(arg1, arg2) {
  return window['go']['main']['App']['FullSyncNpcs'](arg1, arg2);
}

export function FullSyncQuests(arg1, arg2) {
  return window['go']['main']['App']['FullSyncQuests'](arg1, arg2);
}

export function FullSyncSpells(arg1, arg2, arg3) {
  return window['go']['main']['App']['FullSyncSpells'](arg1, arg2, arg3);
}

export function GetAllFavorites() {
  return window['go']['main']['App']['GetAllFavorites']();
}

export function GetCategories() {
  return window['go']['main']['App']['GetCategories']();
}

export function GetCategoryItems(arg1) {
  return window['go']['main']['App']['GetCategoryItems'](arg1);
}

export function GetChildCategories(arg1) {
  return window['go']['main']['App']['GetChildCategories'](arg1);
}

export function GetCreatureDetail(arg1) {
  return window['go']['main']['App']['GetCreatureDetail'](arg1);
}

export function GetCreatureLoot(arg1) {
  return window['go']['main']['App']['GetCreatureLoot'](arg1);
}

export function GetCreatureTypes() {
  return window['go']['main']['App']['GetCreatureTypes']();
}

export function GetFactionDetail(arg1) {
  return window['go']['main']['App']['GetFactionDetail'](arg1);
}

export function GetFactions() {
  return window['go']['main']['App']['GetFactions']();
}

export function GetFavoriteCategories() {
  return window['go']['main']['App']['GetFavoriteCategories']();
}

export function GetFavoritesByCategory(arg1) {
  return window['go']['main']['App']['GetFavoritesByCategory'](arg1);
}

export function GetInstances(arg1) {
  return window['go']['main']['App']['GetInstances'](arg1);
}

export function GetItemClasses() {
  return window['go']['main']['App']['GetItemClasses']();
}

export function GetItemDetail(arg1) {
  return window['go']['main']['App']['GetItemDetail'](arg1);
}

export function GetItemSetDetail(arg1) {
  return window['go']['main']['App']['GetItemSetDetail'](arg1);
}

export function GetItemSets() {
  return window['go']['main']['App']['GetItemSets']();
}

export function GetLocalImage(arg1, arg2) {
  return window['go']['main']['App']['GetLocalImage'](arg1, arg2);
}

export function GetLoot(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetLoot'](arg1, arg2, arg3);
}

export function GetMissingAtlasLootItems(arg1) {
  return window['go']['main']['App']['GetMissingAtlasLootItems'](arg1);
}

export function GetNpcDetails(arg1) {
  return window['go']['main']['App']['GetNpcDetails'](arg1);
}

export function GetObjectDetail(arg1) {
  return window['go']['main']['App']['GetObjectDetail'](arg1);
}

export function GetObjectTypes() {
  return window['go']['main']['App']['GetObjectTypes']();
}

export function GetObjectsByType(arg1, arg2) {
  return window['go']['main']['App']['GetObjectsByType'](arg1, arg2);
}

export function GetQuestCategories() {
  return window['go']['main']['App']['GetQuestCategories']();
}

export function GetQuestCategoriesByGroup(arg1) {
  return window['go']['main']['App']['GetQuestCategoriesByGroup'](arg1);
}

export function GetQuestCategoryGroups() {
  return window['go']['main']['App']['GetQuestCategoryGroups']();
}

export function GetQuestDetail(arg1) {
  return window['go']['main']['App']['GetQuestDetail'](arg1);
}

export function GetQuestsByCategory(arg1) {
  return window['go']['main']['App']['GetQuestsByCategory'](arg1);
}

export function GetQuestsByEnhancedCategory(arg1, arg2) {
  return window['go']['main']['App']['GetQuestsByEnhancedCategory'](arg1, arg2);
}

export function GetRootCategories() {
  return window['go']['main']['App']['GetRootCategories']();
}

export function GetSpellDetail(arg1) {
  return window['go']['main']['App']['GetSpellDetail'](arg1);
}

export function GetSpellSkillCategories() {
  return window['go']['main']['App']['GetSpellSkillCategories']();
}

export function GetSpellSkillsByCategory(arg1) {
  return window['go']['main']['App']['GetSpellSkillsByCategory'](arg1);
}

export function GetSpellsBySkill(arg1, arg2) {
  return window['go']['main']['App']['GetSpellsBySkill'](arg1, arg2);
}

export function GetSyncStats() {
  return window['go']['main']['App']['GetSyncStats']();
}

export function GetTables(arg1, arg2) {
  return window['go']['main']['App']['GetTables'](arg1, arg2);
}

export function GetTooltipData(arg1) {
  return window['go']['main']['App']['GetTooltipData'](arg1);
}

export function IsFavorite(arg1) {
  return window['go']['main']['App']['IsFavorite'](arg1);
}

export function RemoveFavorite(arg1) {
  return window['go']['main']['App']['RemoveFavorite'](arg1);
}

export function SearchCreatures(arg1) {
  return window['go']['main']['App']['SearchCreatures'](arg1);
}

export function SearchItems(arg1) {
  return window['go']['main']['App']['SearchItems'](arg1);
}

export function SearchObjects(arg1) {
  return window['go']['main']['App']['SearchObjects'](arg1);
}

export function SearchQuests(arg1) {
  return window['go']['main']['App']['SearchQuests'](arg1);
}

export function SearchSpells(arg1) {
  return window['go']['main']['App']['SearchSpells'](arg1);
}

export function StopSync() {
  return window['go']['main']['App']['StopSync']();
}

export function SyncMissingAtlasLoot(arg1, arg2) {
  return window['go']['main']['App']['SyncMissingAtlasLoot'](arg1, arg2);
}

export function SyncNpcData(arg1) {
  return window['go']['main']['App']['SyncNpcData'](arg1);
}

export function SyncQuestData(arg1) {
  return window['go']['main']['App']['SyncQuestData'](arg1);
}

export function SyncSingleItem(arg1) {
  return window['go']['main']['App']['SyncSingleItem'](arg1);
}

export function SyncSingleSpell(arg1) {
  return window['go']['main']['App']['SyncSingleSpell'](arg1);
}

export function ToggleFavorite(arg1, arg2) {
  return window['go']['main']['App']['ToggleFavorite'](arg1, arg2);
}

export function UpdateFavoriteCategory(arg1, arg2) {
  return window['go']['main']['App']['UpdateFavoriteCategory'](arg1, arg2);
}

export function UpdateFavoriteStatus(arg1, arg2) {
  return window['go']['main']['App']['UpdateFavoriteStatus'](arg1, arg2);
}

export function WaitForReady() {
  return window['go']['main']['App']['WaitForReady']();
}
