// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AdvancedSearch(arg1) {
  return window['go']['main']['App']['AdvancedSearch'](arg1);
}

export function BrowseItemsByClass(arg1, arg2) {
  return window['go']['main']['App']['BrowseItemsByClass'](arg1, arg2);
}

export function GetCategories() {
  return window['go']['main']['App']['GetCategories']();
}

export function GetCategoryItems(arg1) {
  return window['go']['main']['App']['GetCategoryItems'](arg1);
}

export function GetChildCategories(arg1) {
  return window['go']['main']['App']['GetChildCategories'](arg1);
}

export function GetInstances(arg1) {
  return window['go']['main']['App']['GetInstances'](arg1);
}

export function GetItemClasses() {
  return window['go']['main']['App']['GetItemClasses']();
}

export function GetLoot(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetLoot'](arg1, arg2, arg3);
}

export function GetRootCategories() {
  return window['go']['main']['App']['GetRootCategories']();
}

export function GetTables(arg1, arg2) {
  return window['go']['main']['App']['GetTables'](arg1, arg2);
}

export function GetTooltipData(arg1) {
  return window['go']['main']['App']['GetTooltipData'](arg1);
}

export function SearchItems(arg1) {
  return window['go']['main']['App']['SearchItems'](arg1);
}

export function WaitForReady() {
  return window['go']['main']['App']['WaitForReady']();
}
