// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {database} from '../models';
import {main} from '../models';

export function AdvancedSearch(arg1:database.SearchFilter):Promise<database.SearchResult>;

export function BrowseCreaturesByType(arg1:number):Promise<Array<database.Creature>>;

export function BrowseItemsByClass(arg1:number,arg2:number):Promise<Array<database.Item>>;

export function BrowseItemsByClassAndSlot(arg1:number,arg2:number,arg3:number):Promise<Array<database.Item>>;

export function GetCategories():Promise<Array<string>>;

export function GetCategoryItems(arg1:number):Promise<Array<database.Item>>;

export function GetChildCategories(arg1:number):Promise<Array<database.Category>>;

export function GetCreatureLoot(arg1:number):Promise<Array<database.LootItem>>;

export function GetCreatureTypes():Promise<Array<database.CreatureType>>;

export function GetFactions():Promise<Array<database.Faction>>;

export function GetInstances(arg1:string):Promise<Array<string>>;

export function GetItemClasses():Promise<Array<database.ItemClass>>;

export function GetItemSetDetail(arg1:number):Promise<database.ItemSetDetail>;

export function GetItemSets():Promise<Array<database.ItemSetBrowse>>;

export function GetLoot(arg1:string,arg2:string,arg3:string):Promise<main.LegacyBossLoot>;

export function GetObjectTypes():Promise<Array<database.ObjectType>>;

export function GetObjectsByType(arg1:number):Promise<Array<database.GameObject>>;

export function GetQuestCategories():Promise<Array<database.QuestCategory>>;

export function GetQuestsByCategory(arg1:number):Promise<Array<database.Quest>>;

export function GetRootCategories():Promise<Array<database.Category>>;

export function GetTables(arg1:string,arg2:string):Promise<Array<database.AtlasTable>>;

export function GetTooltipData(arg1:number):Promise<database.TooltipData>;

export function SearchCreatures(arg1:string):Promise<Array<database.Creature>>;

export function SearchItems(arg1:string):Promise<Array<database.Item>>;

export function SearchObjects(arg1:string):Promise<Array<database.GameObject>>;

export function SearchQuests(arg1:string):Promise<Array<database.Quest>>;

export function SearchSpells(arg1:string):Promise<Array<database.Spell>>;

export function WaitForReady():Promise<boolean>;
